---
- name: Create file on semaphore_ubuntu_targets hosts
  hosts: semaphore_ubuntu_targets
  become: yes

  tasks:
    - name: Ensure the file is present
      file:
        path: /home/ubuntu/file.txt
        state: touch

    - name: Add content to the file
      copy:
        content: "This is the content of the file."
        dest: /home/ubuntu/file.txt
